### ISSUE TITLE
selection callback fails if it tries to setState().

### ISSUE THREAD

**Issue by zuotian** [kirjs/react-highcharts#245]
https://jsfiddle.net/44pkw9vp/2/

when the selection fired, and the callback only writes to the console, the zoom action succeed, but when the callback tries to set state for the react component, "this" binding for highchart will fail after the callback, and produce the following error in the console.

Uncaught TypeError: Cannot read property 'zoomY' of undefined
    at https://code.highcharts.com/highcharts.js:378:377
    at Array.forEach (native)
    at a.each (https://code.highcharts.com/highcharts.js:26:471)
    at a.Chart.zoom (https://code.highcharts.com/highcharts.js:378:325)
    at https://code.highcharts.com/highcharts.js:208:508
    at a.fireEvent (https://code.highcharts.com/highcharts.js:29:106)
    at a.Pointer.drop (https://code.highcharts.com/highcharts.js:208:476)
    at HTMLDocument.onDocumentMouseUp (https://code.highcharts.com/highcharts.js:209:450)

**Comment by alfonsomunozpomer** [comment]
I have a similar error when I try to do  a `setState` in the parent component passing a bound callback that’s run in the `setExtremes` event.

My code is:
```
xAxis: {
    events: {
        setExtremes: function(event) {
            this.props.onZoom(event.min !== undefined && event.max !== undefined)
        }.bind(this)
    }
}
```

Some things I tried that may help in debugging...

If I get the reference to `onZoom` at the top of the `render`:
```
const {onZoom} = this.props;
```

And then run the `setExtremes` callback without binding, like this:
```
xAxis: {
    events: {
        setExtremes: function(event) {
            onZoom(event.min !== undefined && event.max !== undefined)
        }
    }
}
```

It turns out that whatever `this` is before and after `onZoom` being invoked changes:
```
xAxis: {
    events: {
        setExtremes: function(event) {
            console.log(this);
            onZoom(event.min !== undefined && event.max !== undefined)
            console.log(this);
        }
    }
}
```

Produces the following output in the browser (Firefox) console:
```
Object { proceed: null, isRadial: false, chart: Object, horiz: true, isXAxis: true, coll: "xAxis", opposite: "true", side: 0, options: Object, labelFormatter: formatter(), 82 more… }  
Object { names: Array[0], series: Array[0], hcEvents: Object, extKey: "0,73", forceRedraw: true, isDirty: true } 
TypeError: this.options is undefined
```

It looks like `this` after the callback is the chart itself, instead of the axis as [per Highcharts documentation](http://api.highcharts.com/highcharts/xAxis.events.setExtremes).

The error is produced in this part of Highcharts code:
```
!h&&c(k)&&(this.resetZoomButton=k.destroy());d&&this.redraw(b(this.options.chart.animation,a&&a.animation,100>this.pointCount))},pan:function(a,b){var c=this,d=c.hoverPoints,e;d&&n(d,function(a){a.setState()});n("xy"===b?[1,0]:[1],function(b){b=c[b?"xAxis":"yAxis"][0];var d=b.horiz,f=a[d?"chartX":"chartY"],d=d?"mouseDownX":"mouseDownY",h=c[d],k=(b.pointRange||0)/2,g=b.getExtremes(),l=b.toValue(h-f,!0)+k,k=b.toValue(h+b.len-f,!0)-k,m=k<l,h=m?k:l,l=m?l:k,m=b.toValue(b.toPixels(g.min)-b.minPixelPadding),
```

If the `onZoom` callback is removed everythin works fine and the reference to `this` doesn’t change.

**Comment by alfonsomunozpomer** [comment]
With version 10.0.0 of react-highcharts the reference to `this` doesn’t change, but the error still happens.

**Comment by alfonsomunozpomer** [comment]
I’ve doing some more testing, and if instead of using a callback (i.e. the React way) you use an `EventEmitter` instance to change the state in the container component, the error keeps happening. This has led me to think that, effectively, what’s going on is that changing the state in the parent component makes react-highcharts call render, and it sets `this` to the chart component within the remainder of the code in the events that are fired after zooming in or out. That `this` reference is the one used, instead of the expected axis.

**Comment by alfonsomunozpomer** [comment]
@zuotian if you want to solve this error there are two workarounds:
1. Don’t use react-highcharts and follow http://www.highcharts.com/blog/post/192-use-highcharts-to-create-charts-in-react/ instead. The changes to the code are minimal.
2. Avoid calling `render` after zooming in/out by explicitly checking that the chart data haven’t changed. This might not be possible if your component state or props change according to the zoomed area, zoom being reset, etc. E.g.:
```
import  hash from 'object-hash';
...
shouldComponentUpdate(nextProps) {
        return hash.MD5(nextProps.chartData)!==hash.MD5(this.props.chartData);
}
```
Kudos to @wbazant for the second approach.

**Comment by zuotian** [comment]
@alfonsomunozpomer, thanks for the investigation. Option 1 is not a choice for me, as my whole application is about charting. But option 2 works like a charm.  :+1:

**Comment by brtdv** [comment]
+1, no real addition, but this is something I'm also still experiencing with `react` v16.6.1 and `react-highcharts-official` v1.5.2.

As mentioned above, better management of the component rendering with `shouldComponentUpdate` avoids the bug. You basically never want the component to re-render after you've executed code that was triggered from an event listener in the Highcharts library.

Just leaving the above breadcrumb for others, because this was something that I couldn't figure out immediately.

**Comment by alfonsomunozpomer** [comment]
It might be worth trying out the [official Highcarts React wrapper](https://github.com/highcharts/highcharts-react). I don’t know if the behaviour will be any different, but [we’ve used it in a different package](https://github.com/ebi-gene-expression-group/scxa-marker-gene-heatmap/blob/feature/161416337-marker-genes-heatmap-component/src/MarkerGeneHeatmap.js) and can be used as a drop-in replacement.

**Comment by kirjs** [comment]
Closing and there has been no activity in this issue for a while.
if this is still relevant, please feel free to reopen

**Comment by hyperbolicme** [comment]
the official wrapper [highcharts-react-official](https://github.com/highcharts/highcharts-react)  does not have this issue
