### ISSUE TITLE
InvalidCharacterError reported by JSDOM using Jest

### ISSUE THREAD

**Issue by hbourzeix** [kirjs/react-highcharts#296]
Steps to reproduce: 
1) create a react app using create-react-app and add react-highcharts
2) update the App.test.js with 

```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import jsdom from 'jsdom';
import ReactHighcharts from 'react-highcharts'; // Expects that Highcharts was loaded in the code.

it('renders without crashing', () => {
  const div = document.createElement('div');

  const config = {
    /* HighchartsConfig */
    chart:{
    }
  };

  ReactDOM.render(<ReactHighcharts config = {config}></ReactHighcharts>,div);
});
```
3) npm t 

result:
```
 InvalidCharacterError
      
      at exports.name (node_modules/jsdom/lib/jsdom/living/helpers/validate-names.js:10:11)
      at DocumentImpl.createElement (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:686:5)
      at Document.createElement (node_modules/jsdom/lib/jsdom/living/generated/Document.js:92:59)
      at a.createElement (node_modules/react-highcharts/node_modules/highcharts/highcharts.js:17:221)
      at Object.init (node_modules/react-highcharts/node_modules/highcharts/highcharts.js:93:38)
      at Object.createElement (node_modules/react-highcharts/node_modules/highcharts/highcharts.js:63:177)
      at Object.createElement (node_modules/react-highcharts/node_modules/highcharts/highcharts.js:108:415)
      at Object.init (node_modules/react-highcharts/node_modules/highcharts/highcharts.js:101:448)
      at Object.B (node_modules/react-highcharts/node_modules/highcharts/highcharts.js:110:234)
      at Object.getContainer (node_modules/react-highcharts/node_modules/highcharts/highcharts.js:254:15)
```

**Comment by mshenfield** [comment]
This is an issue with HighCharts or jsdom, not with react-highcharts.

See jsdom/issues/1791

**Comment by hbourzeix** [comment]
juste to help, I managed to pass using this code in the jsdom setup:
```
var createElementNSOrig = global.document.createElementNS
global.document.createElementNS = function(namespaceURI, qualifiedName) {
  if (namespaceURI==='http://www.w3.org/2000/svg' && qualifiedName==='svg'){
    var element = createElementNSOrig.apply(this,arguments)
    element.createSVGRect = function(){}; // highcharts test this property and fallback to VML with unexpected results
    return element;
  }
  return createElementNSOrig.apply(this,arguments)
}
```
