### ISSUE TITLE
Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by justduy** [kirjs/react-highcharts#310]
I can't get the type arearange chart to work with reach-highcharts. I used a config and data from an example from the Highcharts webpage. 

**The data:**

> const rangesTwo = [
>     [1246406400000, 14.3, 27.7],
>     [1246492800000, 14.5, 27.8],
>     [1246579200000, 15.5, 29.6],
>     [1246665600000, 16.7, 30.7],
>     [1246752000000, 16.5, 25.0],
>     [1246838400000, 17.8, 25.7],
>     [1246924800000, 13.5, 24.8],
>     [1247011200000, 10.5, 21.4],
>     [1247097600000, 9.2, 23.8],
>     [1247184000000, 11.6, 21.8],
>     [1247270400000, 10.7, 23.7],
>     [1247356800000, 11.0, 23.3],
>     [1247443200000, 11.6, 23.7],
>     [1247529600000, 11.8, 20.7],
>     [1247616000000, 12.6, 22.4],
>     [1247702400000, 13.6, 19.6],
>     [1247788800000, 11.4, 22.6],
>     [1247875200000, 13.2, 25.0],
>     [1247961600000, 14.2, 21.6],
>     [1248048000000, 13.1, 17.1],
>     [1248134400000, 12.2, 15.5],
>     [1248220800000, 12.0, 20.8],
>     [1248307200000, 12.0, 17.1],
>     [1248393600000, 12.7, 18.3],
>     [1248480000000, 12.4, 19.4],
>     [1248566400000, 12.6, 19.9],
>     [1248652800000, 11.9, 20.2],
>     [1248739200000, 11.0, 19.3],
>     [1248825600000, 10.8, 17.8],
>     [1248912000000, 11.8, 18.5],
>     [1248998400000, 10.8, 16.1],
>   ];
> 

**The config**
`const options2 = {
    title: {
      text: 'July temperatures',
    },

    xAxis: {
      type: 'datetime',
    },

    yAxis: {
      title: {
        text: null,
      },
    },

    tooltip: {
      crosshairs: true,
      shared: true,
      valueSuffix: '°C',
    },

    legend: {},

    series: [
      {
        name: 'Range',
        data: rangesTwo,
        type: 'arearange',
        color: Highcharts.getOptions().colors[0],
        fillOpacity: 0.3,
        zIndex: 0,
        marker: {
          enabled: false,
        },
      },
    ],
  };`

And then I simply use this config in a:
`      <ReactHighcharts config={options2} />
`

```
Cannot read property 'destroy' of undefined
TypeError: Cannot read property 'destroy' of undefined
    at Object.componentWillUnmount (http://localhost:9009/static/preview.bundle.js:50893:17)
    at Object.chainedFunction [as componentWillUnmount] (http://localhost:9009/static/preview.bundle.js:50470:11)
    at http://localhost:9009/static/preview.bundle.js:30491:25
    at measureLifeCyclePerf (http://localhost:9009/static/preview.bundle.js:30158:12)
    at ReactCompositeComponentWrapper.unmountComponent (http://localhost:9009/static/preview.bundle.js:30490:11)
    at Object.unmountComponent (http://localhost:9009/static/preview.bundle.js:3939:22)
    at Object.unmountChildren (http://localhost:9009/static/preview.bundle.js:30037:25)
    at ReactDOMComponent.unmountChildren (http://localhost:9009/static/preview.bundle.js:34954:28)
    at ReactDOMComponent.unmountComponent (http://localhost:9009/static/preview.bundle.js:32094:10)
    at Object.unmountComponent (http://localhost:9009/static/preview.bundle.js:3939:22)
```

The problem seems to be with the type of chart in the config. Type: Line works perfectly.

**Comment by spencerapplegate** [comment]
I'm getting this same error with a `solidgauge` chart.

react: 15.5.4
react-highcharts: 12.0.0
highcharts: 5.0.12

**Comment by justduy** [comment]
**Versions:** 

react: 15.16.1
highcharts: 5.0.12
react-highcharts: 12.0.0

**Comment by mir3z** [comment]
The same for me:

react: 15.6.1
highcharts: 5.0.15
react-highcharts: 12.0.0

**Comment by smmccrohan** [comment]
Just upgraded from Highcharts 4.27, react-highcharts 10.0.0 to Highcharts 6.0.4, react-highcharts 15.0.0, and I'm getting this error for a chart that previously worked.

**Comment by truetopwebghost** [comment]
I'm using Highchart 6.0.4, react-highcharts 15.0.0, react 15.5.0
and was trying to draw 'solidgauge' chart, but had same problem.
What's the solution?

**Comment by truetopwebghost** [comment]
seems like I've found the solution.
```
import ReactHighChart from 'react-highcharts';
import HighchartsMore from 'highcharts/highcharts-more';
import SolidGauge from 'highcharts/modules/solid-gauge';

...

  constructor (props) {
    super(props);
    HighchartsMore(ReactHighChart.Highcharts);
    SolidGauge(ReactHighChart.Highcharts);
  }

...
```
This works properly.

**Comment by pinturic** [comment]
I am having the same problem with a pie chart after the upgrade. Did someone find a solution? Strange enough the paint is correctly and then the chart disappears.

**Comment by smitthakkar1** [comment]
Having same error. can someone please explain the solution? @truetopwebghost

**Comment by truetopwebghost** [comment]
@smitthakkar1 , According to my experience, most of the issue related with `Cannot read property 'destroy' of undefined` is because of incorrect configuration. Please check your config props again.

**Comment by kirjs** [comment]
Closing and there has been no activity in this issue for a while.
if this is still relevant, please feel free to reopen
