### ISSUE TITLE
Trouble adding highcharts-more

### ISSUE THREAD

**Issue by spyx08** [kirjs/react-highcharts#317]
I've already implemented some charts using react-highcharts without highcharts-more.

A `polar` chart with stacked bar is working fine **without** `highcharts-more`.

For create a `columnrange` chart it wasn't working without highcharts-more. I've find a solution by using `highcharts more` from highcharts library
```
import HighchartMore from 'highcharts/highcharts-more';
HighchartMore(Highchart.Highcharts);
```

When adding highcharts-more my columnrange works but my polar chart have some trouble on the render of the series (bar proportion and positions) and same issue on my spider-web chart.

the chart was working fine befre adding the highcharts-more and is broken (position of series) with the `highcharts-more`

Any idea ?

**Comment by struchkov** [comment]
HighchartMore(Highchart.Highcharts); - must be called once. The repeated call has broken my polar charts.

**Comment by ardok** [comment]
```
import ReactHighcharts from 'react-highcharts';
import HighchartsMore from 'highcharts/highcharts-more';

HighchartsMore(ReactHighcharts.Highcharts);
```

That's all you need to do, right?
Just making sure because I'm encountering some issue
```
TypeError: q is not a function
    at foo/node_modules/highcharts/highcharts-more.js:8:212
    at foo/node_modules/highcharts/highcharts-more.js:11:205
```

**Comment by ilyjs** [comment]
Hi @ardok !
My example https://stackblitz.com/edit/highchartmore?file=HighchartMore.js

**Comment by ardok** [comment]
@ilyjs 
Ah, yeah. Ok.
I forgot that I'm doing SSR. I just needed to only run that `HighchartsMore(ReactHighcharts.Highcharts);` if it's in browser side.
Thanks~

**Comment by kirjs** [comment]
Closing and there has been no activity in this issue for a while.
if this is still relevant, please feel free to reopen
